import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
  imprimante1,
  imprimante2,
  imprimante4,
  imprimante5,
  imprimante6,
  imprimante7,
  imprimante8,
  imprimante9,
  encre1,
  encre2,
  encre3,
  encre4,
  encre5,
  encre6,
  encre7,
  encre8,
  encre9,
  encre10,
  encre11,
  encre12,
  encre13,
  ruban1,
  ruban2,
  ruban3,
  ruban4,
  bac1,
  bac2,
  bac3,
  bac4,
  pdf1,
  IMPRIMANTE_PANTUM_CP2200DW,
  IMPRIMANTE_PANTUM_BM5100FDW,
  IMPRIMANTE_PANTUM_M6609N,
  IMPRIMANTE_PANTUM_P3300DN,
  IMPRIMANTE_PANTUM_P3300DW,
  IMPRIMANTE_PANTUM_P2509W,
  IMPRIMANTE_PANTUM_BP5100DN,
  IMPRIMANTE_PANTUM_M6559N,
  IMPRIMANTE_PANTUM_P2509,
  hp1,
  hp2,
  hp3,
  ricoh1,
  ricoh2,
  ricoh3,
  ricoh4,
  ricoh5,
  espson1,
  espson2,
  encre14,
  encre15,
  encre16,
  encre17,
  encre18,
  encre19,
  encre20,
  encre21,
  encre22,
} from "../assets/images/index";

import "./style.css";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  {
    _id: 1005,
    title: "Journal",
    link: "/journal",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: imprimante1,
    productName: "imprimante",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "202",
    img: imprimante2,
    productName: "imprimante",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "203",
    img: imprimante4,
    productName: "imprimante",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "204",
    img: imprimante5,
    productName: "imprimante",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "205",
    img: imprimante6,
    productName: "imprimante",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "206",
    img: imprimante7,
    productName: "imprimante",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "207",
    img: imprimante8,
    productName: "imprimante",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "208",
    img: imprimante9,
    productName: "imprimante",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "209",
    img: encre1,
    productName: "encre",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "ancre",
  },
  {
    _id: "210",
    img: encre2,
    productName: "encre",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "ancre",
  },
  {
    _id: "211",
    img: encre3,
    productName: "encre",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "ancre",
  },
  {
    _id: "212",
    img: encre4,
    productName: "encre",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "ancre",
  },
  {
    _id: "213",
    img: ruban1,
    productName: "Ruban",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Ruban",
  },
  {
    _id: "214",
    img: ruban2,
    productName: "Ruban",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Ruban",
  },
  {
    _id: "215",
    img: ruban3,
    productName: "Ruban",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Ruban",
  },
  {
    _id: "216",
    img: ruban4,
    productName: "Ruban",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Ruban",
  },
  {
    _id: "217",
    img: bac1,
    productName: "Bac de dechet",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Bac",
  },
  {
    _id: "219",
    img: bac2,
    productName: "Bac de dechet",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Bac",
  },
  {
    _id: "220",
    img: bac3,
    productName: "Bac de dechet",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Bac",
  },
  {
    _id: "221",
    img: bac4,
    productName: "Bac de dechet",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Bac",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: "201",
    img: encre5,
    productName: "Serum",
    price: "35.00",
    color: "Brown",
    badge: true,
    brand: "Pantum",
    des: "Best Serum For Skin",
    cat: "Imprimante",
    pdf: pdf1,
    ficheTech: [
      { label: "Technology ", value: "Electrophotographic monochrome laser " },
      { label: "Print speed ", value: "22 ppm (A4)/23 ppm (Letter)" },

      { label: "First print out time ", value: "Less than 7.8s       " },
      { label: "Maximum Monthly Duty Cycle", value: "15,000 pages " },
      {
        label: "Recommended monthly volume Resolution(dpi) ",
        value: "700 pages ",
      },
      { label: "Printer language Duplex Mode ", value: "Max. 1,200×1,200 " },
      { label: "Printer  ", value: "Max. 1,2   " },
      { label: "galass  ", value: "Max. 1,2   " },
    ],
  },
  {
    _id: "202",
    img: encre6,
    productName: "Face Cream",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "Best Face Cream For Skin",
    cat: "Imprimante",
    pdf: pdf1,
    ficheTech: [
      { label: "Vitesse d'impression ", value: "40ppm(A4)/42ppm(lettre) " },
      { label: "Temps de sortie de la première page ", value: "≤6.9 s" },

      {
        label: "Nombre de pages mensuel recommandé",
        value: "750 à 4,000 Pages",
      },
      { label: "Résolution d'impression", value: "Max.1,200x1,200 dpi" },
      {
        label: "Langage d'impression ",
        value: "PCL5e, PCL6, PS        ",
      },
      { label: "Vitesse du processeur", value: "1.2 GHz" },
      { label: "Mémoire", value: "512 MB" },
      {
        label: "Panneau de commande ",
        value: "LCD 2 lignes ||  Écran tactile 3,5 pouces      ",
      },
      { label: "Impression recto-verso automatique      ", value: "Oui" },
      {
        label: "Autres fonctions d'impression      ",
        value:
          "Impression brochure, impression sécurisée, impression disque USB Compatible AirPrint, Mopria, APP mobile (APP iOS/App Android)",
      },
      { label: "Vitese de copie ", value: "40ppm(A4)/42ppm(lettre)" },
      {
        label: "Temps de sortie de la première page",
        value: "Plateau : moins de 10 s ADF : moins de 11 s",
      },
    ],
  },

  {
    _id: "203",
    img: encre7,
    productName: "Body Lotion",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "Best Body Lotion For Skin",
    cat: "Imprimante",
    pdf: pdf1,
    ficheTech: [
      { label: "Vitesse d'impression ", value: "40ppm(A4)/42ppm(lettre) " },
      { label: "Temps de sortie de la première page ", value: "≤6.9 s" },

      {
        label: "Nombre de pages mensuel recommandé",
        value: "750 à 4,000 Pages",
      },
      { label: "Résolution d'impression", value: "Max.1,200x1,200 dpi" },
      {
        label: "Langage d'impression ",
        value: "PCL5e, PCL6, PS        ",
      },
      { label: "Vitesse du processeur", value: "1.2 GHz" },
      { label: "Mémoire", value: "512 MB" },
      {
        label: "Panneau de commande ",
        value: "LCD 2 lignes ||  Écran tactile 3,5 pouces      ",
      },
      { label: "Impression recto-verso automatique      ", value: "Oui" },
      {
        label: "Autres fonctions d'impression      ",
        value:
          "Impression brochure, impression sécurisée, impression disque USB Compatible AirPrint, Mopria, APP mobile (APP iOS/App Android)",
      },
      { label: "Vitese de copie ", value: "40ppm(A4)/42ppm(lettre)" },
      {
        label: "Temps de sortie de la première page",
        value: "Plateau : moins de 10 s ADF : moins de 11 s",
      },
    ],
  },
  {
    _id: "2005",
    img: encre8,
    productName: "Face Wash",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "Best Face Wash For Skin",
    cat: "Imprimante",
    pdf: pdf1,
    ficheTech: [
      { label: "gtin	", value: "M6559N      " },
      { label: "Marque	", value: "PANTUM      " },
      { label: "fonctions	", value: "Monofonction      " },
      { label: "Technologie d impression		", value: "Laser      " },
      { label: "Impression	", value: "Noir & Blanc      " },
      { label: "Vitesse du Processeur		", value: "600MHz      " },
      {
        label: "Capacité papier		",
        value: "Capacité standard: 1 600 pages      ",
      },
      { label: "Gestion d entrée Papier Standard		", value: "150 pages      " },
      { label: "Premiére Page Imprimée		", value: "Moins de 7.8s      " },
      { label: "Cycle d utilisation Mensuel		", value: "15 000 pages      " },
      {
        label: "Résolution d impression		",
        value: "Max. 1 200 × 1 200 ppp      ",
      },
      {
        label: "Résolution d'impression Noir		",
        value: "Max. 1 200 × 1 200 ppp      ",
      },
      { label: "formats		", value: "A4      " },
      { label: "Sortie papier		", value: "100 pages      " },
      {
        label: "Vitesse de Copie Noir Blanc		",
        value: "22 ppm (A4) / 23 ppm (Lettre)      ",
      },
      { label: "Poids		", value: "4,75 kg      " },
    ],
  },

  {
    _id: "20005",
    img: encre9,
    productName: "Serum",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "best serum for skin",
    cat: "Imprimante",
    pdf: pdf1,
    ficheTech: [
      { label: "gtin	", value: "M6559N      " },
      { label: "Marque	", value: "PANTUM      " },
      { label: "fonctions	", value: "Monofonction      " },
      { label: "Technologie d impression		", value: "Laser      " },
      { label: "Impression	", value: "Noir & Blanc      " },
      { label: "Vitesse du Processeur		", value: "600MHz      " },
      {
        label: "Capacité papier		",
        value: "Capacité standard: 1 600 pages      ",
      },
      { label: "Gestion d entrée Papier Standard		", value: "150 pages      " },
      { label: "Premiére Page Imprimée		", value: "Moins de 7.8s      " },
      { label: "Cycle d utilisation Mensuel		", value: "15 000 pages      " },
      {
        label: "Résolution d impression		",
        value: "Max. 1 200 × 1 200 ppp      ",
      },
      {
        label: "Résolution d'impression Noir		",
        value: "Max. 1 200 × 1 200 ppp      ",
      },
      { label: "formats		", value: "A4      " },
      { label: "Sortie papier		", value: "100 pages      " },
      {
        label: "Vitesse de Copie Noir Blanc		",
        value: "22 ppm (A4) / 23 ppm (Lettre)      ",
      },
      { label: "Poids		", value: "4,75 kg      " },
    ],
  },

  {
    _id: "206",
    img: encre10,
    productName: "Face Wash",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "best face wash for skin",
    cat: "Imprimante",
    pdf: pdf1,
    ficheTech: [
      { label: "gtin	", value: "P3300DN      " },
      { label: "fonctions	", value: "Monofonction      " },
      { label: "Mémoire	", value: "256MO      " },
      { label: "Technologie d impression		", value: "laser      " },
      { label: "Impression		", value: "Noir & Blanc      " },
      { label: "Connectivite		", value: "Réseau      " },
      { label: "Vitesse du Processeur		", value: "350 MHz      " },
      { label: "Type ecran		", value: "LCD 2 lignes      " },
      {
        label: "Consommation d énergie		",
        value:
          "Impression : 525 W en moyenne Veille : 50 W en veille : moins de 2 W      ",
      },
      {
        label: "Gestion d entrée Papier Standard		",
        value: "Papier Bac d'alimentation: 250pages      ",
      },
      { label: "Premiére Page Imprimée		", value: "Moins de 8,2 secondes      " },
      {
        label: "Vitesse d impression Noir		",
        value: "33 ppm (A4) / 35 ppm (Lettre)      ",
      },
      { label: "Cycle d utilisation Mensuel		", value: "60000pages      " },
      {
        label: "Résolution d impression		",
        value: "1 200 x 1 200 dpi (maximum)      ",
      },
      { label: "formats	", value: "A4      " },
      {
        label: "Connecteurs		",
        value: "USB2.0 haut débit / Ethernet：IEEE 802.3 10/100Base-Tx      ",
      },
      { label: "Fonctionnalités		", value: "Impression      " },
      {
        label: "Volume de Pages Mensuel Recommandé		",
        value: "750 à 3 500 pages      ",
      },
      { label: "Dimensions		", value: "354 x 334 x 232mm      " },
      { label: "Garantie	", value: "1ANS      " },
    ],
  },

  {
    _id: "207",
    img: encre11,
    productName: "Face Cream",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "best face cream for skin",
    cat: "Imprimante",
    pdf: pdf1,
    ficheTech: [
      { label: "gtin		", value: "P3300DW      " },
      { label: "fonctions	", value: "Monofonction      " },
      { label: "Mémoire	", value: "256 Mo      " },
      { label: "Technologie d impression		", value: "Laser      " },
      { label: "Connectivite	", value: "WIFI      " },
      { label: "Vitesse du Processeur		", value: "350 MHz      " },
      { label: "Type ecran		", value: "LCD 2 lignes      " },
      {
        label: "Consommation d énergie		",
        value:
          "Impression : 525 W en moyenne Veille : 50 W en veille : moins de 2 W      ",
      },
      {
        label: "Gestion d entrée Papier Standard		",
        value: "Papier Bac d'alimentation: 250pages      ",
      },
      { label: "Premiére Page Imprimée		", value: "Moins de 8,2 secondes      " },
      {
        label: "Vitesse d impression Noir		",
        value: "33 ppm (A4) / 35 ppm (Lettre)      ",
      },
      { label: "Cycle d utilisation Mensuel		", value: "60000pages      " },
      { label: "Résolution d impression		", value: "Max.1200x1200 dpi      " },
      {
        label: "Volume de Pages Mensuel Recommandé		",
        value: "750 à 3 500 pages      ",
      },
      {
        label: "Interface Réseau	",
        value:
          "Ethernet USB 2.0 haut débit : Wi-Fi IEEE 802.3 10/100Base-Tx : IEEE 802.11b/g/n      ",
      },
      {
        label: "Contenu de L'emballage		",
        value:
          "Imprimante - Cordon d’alimentation - Câble d’interface USB - Plateau de sortie - CD-ROM - Guide de configuration rapide      ",
      },
      { label: "Garantie	", value: "1 ANS      " },
    ],
  },

  {
    _id: "208",
    img: encre12,
    productName: "Body Lotion",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "best body lotion for skin",
    cat: "Imprimante",
    pdf: pdf1,
    ficheTech: [
      { label: "gtin	", value: "P2509W      " },
      { label: "fonctions	", value: "Monofonction      " },
      { label: "Technologie d impression		", value: "Laser      " },
      { label: "Ecran Tactile		", value: "Non      " },
      { label: "Connectivite	", value: "WiFi      " },
      { label: "Vitesse du Processeur		", value: "600MHz      " },
      {
        label: "Capacité papier		",
        value: "Capacité standard: 1 600 pages      ",
      },
      { label: "Premiére Page Imprimée		", value: "Moins de 7.8s      " },
      { label: "Cycle d utilisation Mensuel		", value: "15 000 pages      " },
      {
        label: "Résolution d impression		",
        value: "Max. 1 200 × 1 200 ppp      ",
      },
      { label: "formats	", value: "A4      " },
      { label: "Connecteurs		", value: "USB 2.0, Wi-Fi      " },
      {
        label: "Vitesse de Copie Noir Blanc		",
        value: "22 ppm (A4) / 23 ppm (Lettre)      ",
      },
      {
        label: "Contenu de L'emballage		",
        value:
          "Imprimante - Cordon d’alimentation - Câble d’interface USB - Plateau de sortie - CD-ROM - Guide de configuration rapide      ",
      },
      { label: "Dimensions		", value: "337 x 220 x 178 mm      " },
    ],
  },
  {
    _id: "233",
    img: encre13,
    productName: "Serum",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "best serum for skin",
    cat: "Imprimante",
    pdf: pdf1,
    ficheTech: [],
  },
  {
    _id: "220",
    img: encre14,
    productName: "Body Spray",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "best body spray for skin",
    cat: "Bac",
  },
  {
    _id: "221",
    img: encre15,
    productName: "Body Lotion",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "best body lotion for skin",
    cat: "Bac",
  },
  {
    _id: "215",
    img: encre16,
    productName: "Face Cream",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "best face cream for skin",
    cat: "Ruban",
  },
  {
    _id: "216",
    img: encre17,
    productName: "Ruban",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Ruban",
  },
  {
    _id: "209",
    img: encre18,
    productName: "Face Wash",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "best face wash for skin",
    cat: "Encre",
  },
  {
    _id: "210",
    img: encre19,
    productName: "Body Lotion",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "best body lotion for skin",
    cat: "Encre",
  },

  {
    _id: "211",
    img: encre20,
    productName: "Face Scrubber",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "best Face Scrubber for skin",
    cat: "Encre",
  },
  {
    _id: "212",
    img: encre21,
    productName: "Face Cream",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "best face cream for skin",
    cat: "Encre",
  },
  {
    _id: "213",
    img: encre22,
    productName: "Serum",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "best serumfor skin",
    cat: "Ruban",
  },
  // {
  //   _id: "214",
  //   img: ruban2,
  //   productName: "Ruban",
  //   price: "220.00",
  //   color: "Black",
  //   badge: true,
  //   des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  //   cat: "Ruban",
  // },

  // {
  //   _id: "217",
  //   img: bac1,
  //   productName: "Bac de dechet",
  //   price: "25.00",
  //   color: "Mixed",
  //   badge: true,
  //   des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  //   cat: "Bac",
  // },
  // {
  //   _id: "219",
  //   img: bac2,
  //   productName: "Bac de dechet",
  //   price: "220.00",
  //   color: "Black",
  //   badge: true,
  //   des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  //   cat: "Bac",
  // },

  // =================== imprimante hp =================

  // {
  //   _id: "hp1",
  //   img: hp1,
  //   productName:
  //     "IMPRIMANTE HP JET D'ENCRE HP SMART TANK 516 COULEUR MFP 3EN1 A4 WIFI",
  //   price: "450",
  //   color: "Blanc",
  //   badge: true,
  //   brand: "Hp",
  //   des: "Desc : Imprimante Jet D'encre HP SMART TANK 516 3en1 Couleur 3YW70A - Fonction: Impression, Copie, Numérisation - Technologie d'impression: jet d'encre - Vitesse d'impression Noir : Jusqu'à 22 ppm - Vitesse d’impression Couleur : Jusqu'à 16 ppm - Résolution d'impression Couleur : 1200x1200dpi - Format Papier : A4 - Capacité Papier : 100 feuilles -  Cycle d'utilisation (mensuel, A4) : Jusqu'à 1000pages - Connectivité: USB 2.0 haute vitesse, Wi-Fi, Bluetooth LE -  Dimensions: 447 x 373 x 158 mm - Garantie: 1 an",
  //   cat: "Imprimante",
  //   pdf: pdf1,
  //   ficheTech: [
  //     { label: "DISPONIBILITÉ", value: "En stock" },
  //     { label: "gtin", value: "3YW70A" },
  //     { label: "Marque", value: "HP" },
  //     { label: "Destockage", value: "Non" },
  //     { label: "Ecran", value: "LCD" },
  //     {
  //       label: "Taille de L écran cm",
  //       value: "Affichage LCD 7 segments + icône 5,08 cm (2 pouces)",
  //     },
  //     { label: "Ecran Tactile", value: "Non" },
  //     { label: "Technologie d impression", value: "Jet d'encre" },
  //     { label: "fonctions", value: "Multifonction" },
  //     { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
  //     { label: "Impression", value: "Couleur" },
  //     { label: "formats", value: "A4" },
  //     { label: "Chargement de Documents", value: "Oui" },
  //     { label: "Vitesse d impression Noir", value: "Jusqu'à 22 ppm" },
  //     { label: "Vitesse d impression Couleur", value: "Jusqu'à 16 ppm" },
  //     { label: "FAX", value: "Non" },
  //     { label: "Mémoire", value: "256 Mo" },
  //     {
  //       label: "Qualité d impression Noir",
  //       value: "Jusqu'à 1 200 x 1 200 ppp",
  //     },
  //     {
  //       label: "Qualité d impression Couleur",
  //       value: "Jusqu'à 4 800 x 1 200 ppp",
  //     },
  //     { label: "Résolution d impression Couleur", value: "1200x1200dpi" },
  //     { label: "Recto/Verso", value: "Manuel" },
  //     { label: "Type de Scanner", value: "Scanner à Plat" },
  //     { label: "Connectivite", value: "USB 2.0, WiFi" },
  //     { label: "Capacité papier", value: "100 feuilles" },
  //     { label: "Cycle d utilisation Mensuel", value: "Jusqu'à 1000 pages" },
  //     {
  //       label: "Consommation électrique",
  //       value:
  //         "0,12 Watts (Arrêt manuel), 3,12 Watts (Prêt), 0,75 Watt (Veille) 5",
  //     },
  //     { label: "Grammage", value: "75 g/m²" },
  //     {
  //       label: "Contenu de L'emballage",
  //       value:
  //         "Imprimante HP Smart Tank 516, Bouteilles d'encre: 3 x HP GT53XL (noir), 3 x HP GT52 (cyan, magenta et jaune), Notice de précaution pour l'encre; Fiche pour le ré-emballage et réglementaire RoH-EAC; Cordon d'alimentation, Guide d'installation; Notice PT",
  //     },
  //     { label: "Poids", value: "5,14 kg" },
  //     { label: "Dimensions", value: "447 x 373 x 158 mm" },
  //     { label: "Couleur", value: "Noir et Bleu" },
  //     { label: "Garantie", value: "1 an" },
  //   ],
  // },

  // {
  //   _id: "hp2",
  //   img: hp2,
  //   productName: "IMPRIMANTE HP INK TANK WIRELESS 415 ALL-IN-ONE",
  //   price: "450",
  //   color: "Blanc",
  //   badge: true,
  //   brand: "Hp",
  //   des: "Desc : Imprimante Multifonction Jet d'encre 3 en 1 à réservoir intégré - Impression, numérisation, copie, sans fil - Résolution d'impression: Jusqu'à 4800 x 1200 dpi - Vitesse d'impression Couleur Jusqu'à 15 ppm -Vitesse d'impression N et B Jusqu'à 18 ppm - Résolution du scanner: 1200 x 1200 dpi - Format A4 - Interface USB - Bac d'alimentation de 60 feuilles - Dimensions: 525 x 310 x 158 mm - Garantie 1 an (+ Extension de Garantie 2 Ans ) + 5 Bouteilles",
  //   cat: "Imprimante",
  //   pdf: pdf1,
  //   ficheTech: [],
  // },

  // {
  //   _id: "hp3",
  //   img: hp3,
  //   productName: "IMPRIMANTE HP INK TANK WIRELESS 415 ALL-IN-ONE",
  //   price: "450",
  //   color: "Blanc",
  //   badge: true,
  //   brand: "Hp",
  //   des: "Imprimante à Réservoir intégré HP Ink Tank 315 - Fonctions: Impression, copier, Numérisation - Format Papier: A4 - Technologie d'impression: jet d'encre thermique HP - Vitesse d'impression: Jusqu'à 19 ppm (Noir), Jusqu'à 15 ppm (couleur) - Résolution d'impression: 1200 x 1200 dpi(couleur), 4800 x 1200 dpi(noir) - Vitesse de copie(A4, ISO): 6,5 cpm Noir; 2 cpm Couleur - Vitesse de numérisation A4: Jusqu'à 21 secondes - Impression recto verso Manuelle - Formats de fichiers pour la numérisation: JPEG, TIFF, PDF, BMP, PNG - Vitesse du processeur: 360 MHz - Connectivité: USB  - Dimensions: 525 x 310 x 158 mm - Poids: 4,67 kg - Garantie: 1 an",
  //   cat: "Imprimante",
  //   pdf: pdf1,
  //   ficheTech: [
  //     { label: "DISPONIBILITÉ", value: "En stock" },
  //     { label: "gtin", value: "Z4B04A" },
  //     { label: "Marque", value: "HP" },
  //     { label: "Destockage", value: "Non" },
  //     { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
  //     { label: "fonctions", value: "Multifonction" },
  //     { label: "Impression", value: "Couleur" },
  //     { label: "Mémoire", value: "Non" },
  //     { label: "FAX", value: "Non" },
  //     { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
  //     { label: "Chargement de Documents", value: "Oui" },
  //     { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
  //     { label: "Vitesse du Processeur", value: "360 MHz" },
  //     {
  //       label: "Impression sans bordure",
  //       value: "Oui, jusqu’à 210 x 297 mm (A4)",
  //     },
  //     { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
  //     { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
  //     {
  //       label: "Résolution d'impression Noir",
  //       value: "Jusqu'à 1 200 x 1 200 DPI",
  //     },
  //     {
  //       label: "Résolution d impression Couleur",
  //       value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
  //     },
  //     {
  //       label: "Résolution d impression",
  //       value:
  //         "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
  //     },
  //     { label: "Type de Scanner", value: "Scanner à Plat" },
  //     { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
  //     { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
  //     {
  //       label: "Résolution de numérisation optimisée",
  //       value: "Jusqu’à 1200 ppp",
  //     },
  //     { label: "Recto/Verso", value: "Manuel" },
  //     { label: "Connectivite", value: "USB" },
  //     { label: "formats", value: "A4" },
  //     {
  //       label: "Premiére Page Imprimée",
  //       value:
  //         "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
  //     },
  //     {
  //       label: "Alimentation-courant",
  //       value:
  //         "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
  //     },
  //     {
  //       label: "Type de Papier pris en charge",
  //       value:
  //         "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
  //     },
  //     {
  //       label: "Consommation électrique",
  //       value:
  //         "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
  //     },
  //     {
  //       label: "Cycle d utilisation Mensuel",
  //       value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
  //     },
  //     {
  //       label: "Alimentation papier standard",
  //       value:
  //         "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
  //     },
  //     { label: "Ecran Tactile", value: "Non" },
  //     { label: "Type ecran", value: "7 segments et icône LCD" },
  //     {
  //       label: "Volume de Pages Mensuel Recommandé",
  //       value: "400 à 800 (Jusqu'à 1000 pages)",
  //     },
  //     { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
  //     { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
  //     { label: "Grammage", value: "75 g/m²" },
  //     {
  //       label: "Contenu de L'emballage",
  //       value:
  //         "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
  //     },
  //     { label: "Poids", value: "4,67 kg" },
  //     { label: "Couleur", value: "Noir" },
  //     { label: "Dimensions", value: "525 x 310 x 158 mm" },
  //     { label: "Garantie", value: "1 an" },
  //   ],
  // },
  // =================== imprimante ricoh =================
  // {
  //   _id: "ricoh1",
  //   img: ricoh1,
  //   productName: "IMPRIMANTE RICOH P501",
  //   price: "450",
  //   color: "Blanc",
  //   badge: true,
  //   brand: "Ricoh",
  //   des: "Imprimante à Réservoir intégré HP Ink Tank 315 - Fonctions: Impression, copier, Numérisation - Format Papier: A4 - Technologie d'impression: jet d'encre thermique HP - Vitesse d'impression: Jusqu'à 19 ppm (Noir), Jusqu'à 15 ppm (couleur) - Résolution d'impression: 1200 x 1200 dpi(couleur), 4800 x 1200 dpi(noir) - Vitesse de copie(A4, ISO): 6,5 cpm Noir; 2 cpm Couleur - Vitesse de numérisation A4: Jusqu'à 21 secondes - Impression recto verso Manuelle - Formats de fichiers pour la numérisation: JPEG, TIFF, PDF, BMP, PNG - Vitesse du processeur: 360 MHz - Connectivité: USB  - Dimensions: 525 x 310 x 158 mm - Poids: 4,67 kg - Garantie: 1 an",
  //   cat: "Imprimante",
  //   pdf: pdf1,
  //   ficheTech: [
  //     { label: "DISPONIBILITÉ", value: "En stock" },
  //     { label: "gtin", value: "Z4B04A" },
  //     { label: "Marque", value: "HP" },
  //     { label: "Destockage", value: "Non" },
  //     { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
  //     { label: "fonctions", value: "Multifonction" },
  //     { label: "Impression", value: "Couleur" },
  //     { label: "Mémoire", value: "Non" },
  //     { label: "FAX", value: "Non" },
  //     { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
  //     { label: "Chargement de Documents", value: "Oui" },
  //     { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
  //     { label: "Vitesse du Processeur", value: "360 MHz" },
  //     {
  //       label: "Impression sans bordure",
  //       value: "Oui, jusqu’à 210 x 297 mm (A4)",
  //     },
  //     { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
  //     { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
  //     {
  //       label: "Résolution d'impression Noir",
  //       value: "Jusqu'à 1 200 x 1 200 DPI",
  //     },
  //     {
  //       label: "Résolution d impression Couleur",
  //       value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
  //     },
  //     {
  //       label: "Résolution d impression",
  //       value:
  //         "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
  //     },
  //     { label: "Type de Scanner", value: "Scanner à Plat" },
  //     { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
  //     { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
  //     {
  //       label: "Résolution de numérisation optimisée",
  //       value: "Jusqu’à 1200 ppp",
  //     },
  //     { label: "Recto/Verso", value: "Manuel" },
  //     { label: "Connectivite", value: "USB" },
  //     { label: "formats", value: "A4" },
  //     {
  //       label: "Premiére Page Imprimée",
  //       value:
  //         "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
  //     },
  //     {
  //       label: "Alimentation-courant",
  //       value:
  //         "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
  //     },
  //     {
  //       label: "Type de Papier pris en charge",
  //       value:
  //         "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
  //     },
  //     {
  //       label: "Consommation électrique",
  //       value:
  //         "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
  //     },
  //     {
  //       label: "Cycle d utilisation Mensuel",
  //       value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
  //     },
  //     {
  //       label: "Alimentation papier standard",
  //       value:
  //         "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
  //     },
  //     { label: "Ecran Tactile", value: "Non" },
  //     { label: "Type ecran", value: "7 segments et icône LCD" },
  //     {
  //       label: "Volume de Pages Mensuel Recommandé",
  //       value: "400 à 800 (Jusqu'à 1000 pages)",
  //     },
  //     { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
  //     { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
  //     { label: "Grammage", value: "75 g/m²" },
  //     {
  //       label: "Contenu de L'emballage",
  //       value:
  //         "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
  //     },
  //     { label: "Poids", value: "4,67 kg" },
  //     { label: "Couleur", value: "Noir" },
  //     { label: "Dimensions", value: "525 x 310 x 158 mm" },
  //     { label: "Garantie", value: "1 an" },
  //   ],
  // },

  // {
  //   _id: "ricoh2",
  //   img: ricoh2,
  //   productName: "IMPRIMANTE RICOH SP3710DN",
  //   price: "450",
  //   color: "Blanc",
  //   badge: true,
  //   brand: "Ricoh",
  //   des: "Imprimante à Réservoir intégré HP Ink Tank 315 - Fonctions: Impression, copier, Numérisation - Format Papier: A4 - Technologie d'impression: jet d'encre thermique HP - Vitesse d'impression: Jusqu'à 19 ppm (Noir), Jusqu'à 15 ppm (couleur) - Résolution d'impression: 1200 x 1200 dpi(couleur), 4800 x 1200 dpi(noir) - Vitesse de copie(A4, ISO): 6,5 cpm Noir; 2 cpm Couleur - Vitesse de numérisation A4: Jusqu'à 21 secondes - Impression recto verso Manuelle - Formats de fichiers pour la numérisation: JPEG, TIFF, PDF, BMP, PNG - Vitesse du processeur: 360 MHz - Connectivité: USB  - Dimensions: 525 x 310 x 158 mm - Poids: 4,67 kg - Garantie: 1 an",
  //   cat: "Imprimante",
  //   pdf: pdf1,
  //   ficheTech: [
  //     { label: "DISPONIBILITÉ", value: "En stock" },
  //     { label: "gtin", value: "Z4B04A" },
  //     { label: "Marque", value: "HP" },
  //     { label: "Destockage", value: "Non" },
  //     { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
  //     { label: "fonctions", value: "Multifonction" },
  //     { label: "Impression", value: "Couleur" },
  //     { label: "Mémoire", value: "Non" },
  //     { label: "FAX", value: "Non" },
  //     { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
  //     { label: "Chargement de Documents", value: "Oui" },
  //     { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
  //     { label: "Vitesse du Processeur", value: "360 MHz" },
  //     {
  //       label: "Impression sans bordure",
  //       value: "Oui, jusqu’à 210 x 297 mm (A4)",
  //     },
  //     { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
  //     { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
  //     {
  //       label: "Résolution d'impression Noir",
  //       value: "Jusqu'à 1 200 x 1 200 DPI",
  //     },
  //     {
  //       label: "Résolution d impression Couleur",
  //       value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
  //     },
  //     {
  //       label: "Résolution d impression",
  //       value:
  //         "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
  //     },
  //     { label: "Type de Scanner", value: "Scanner à Plat" },
  //     { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
  //     { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
  //     {
  //       label: "Résolution de numérisation optimisée",
  //       value: "Jusqu’à 1200 ppp",
  //     },
  //     { label: "Recto/Verso", value: "Manuel" },
  //     { label: "Connectivite", value: "USB" },
  //     { label: "formats", value: "A4" },
  //     {
  //       label: "Premiére Page Imprimée",
  //       value:
  //         "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
  //     },
  //     {
  //       label: "Alimentation-courant",
  //       value:
  //         "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
  //     },
  //     {
  //       label: "Type de Papier pris en charge",
  //       value:
  //         "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
  //     },
  //     {
  //       label: "Consommation électrique",
  //       value:
  //         "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
  //     },
  //     {
  //       label: "Cycle d utilisation Mensuel",
  //       value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
  //     },
  //     {
  //       label: "Alimentation papier standard",
  //       value:
  //         "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
  //     },
  //     { label: "Ecran Tactile", value: "Non" },
  //     { label: "Type ecran", value: "7 segments et icône LCD" },
  //     {
  //       label: "Volume de Pages Mensuel Recommandé",
  //       value: "400 à 800 (Jusqu'à 1000 pages)",
  //     },
  //     { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
  //     { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
  //     { label: "Grammage", value: "75 g/m²" },
  //     {
  //       label: "Contenu de L'emballage",
  //       value:
  //         "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
  //     },
  //     { label: "Poids", value: "4,67 kg" },
  //     { label: "Couleur", value: "Noir" },
  //     { label: "Dimensions", value: "525 x 310 x 158 mm" },
  //     { label: "Garantie", value: "1 an" },
  //   ],
  // },
  // {
  //   _id: "ricoh3",
  //   img: ricoh3,
  //   productName: "IMPRIMANTE RICOH SP4520DN",
  //   price: "450",
  //   color: "Blanc",
  //   badge: true,
  //   brand: "Ricoh",
  //   des: "Imprimante à Réservoir intégré HP Ink Tank 315 - Fonctions: Impression, copier, Numérisation - Format Papier: A4 - Technologie d'impression: jet d'encre thermique HP - Vitesse d'impression: Jusqu'à 19 ppm (Noir), Jusqu'à 15 ppm (couleur) - Résolution d'impression: 1200 x 1200 dpi(couleur), 4800 x 1200 dpi(noir) - Vitesse de copie(A4, ISO): 6,5 cpm Noir; 2 cpm Couleur - Vitesse de numérisation A4: Jusqu'à 21 secondes - Impression recto verso Manuelle - Formats de fichiers pour la numérisation: JPEG, TIFF, PDF, BMP, PNG - Vitesse du processeur: 360 MHz - Connectivité: USB  - Dimensions: 525 x 310 x 158 mm - Poids: 4,67 kg - Garantie: 1 an",
  //   cat: "Imprimante",
  //   pdf: pdf1,
  //   ficheTech: [
  //     { label: "DISPONIBILITÉ", value: "En stock" },
  //     { label: "gtin", value: "Z4B04A" },
  //     { label: "Marque", value: "HP" },
  //     { label: "Destockage", value: "Non" },
  //     { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
  //     { label: "fonctions", value: "Multifonction" },
  //     { label: "Impression", value: "Couleur" },
  //     { label: "Mémoire", value: "Non" },
  //     { label: "FAX", value: "Non" },
  //     { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
  //     { label: "Chargement de Documents", value: "Oui" },
  //     { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
  //     { label: "Vitesse du Processeur", value: "360 MHz" },
  //     {
  //       label: "Impression sans bordure",
  //       value: "Oui, jusqu’à 210 x 297 mm (A4)",
  //     },
  //     { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
  //     { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
  //     {
  //       label: "Résolution d'impression Noir",
  //       value: "Jusqu'à 1 200 x 1 200 DPI",
  //     },
  //     {
  //       label: "Résolution d impression Couleur",
  //       value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
  //     },
  //     {
  //       label: "Résolution d impression",
  //       value:
  //         "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
  //     },
  //     { label: "Type de Scanner", value: "Scanner à Plat" },
  //     { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
  //     { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
  //     {
  //       label: "Résolution de numérisation optimisée",
  //       value: "Jusqu’à 1200 ppp",
  //     },
  //     { label: "Recto/Verso", value: "Manuel" },
  //     { label: "Connectivite", value: "USB" },
  //     { label: "formats", value: "A4" },
  //     {
  //       label: "Premiére Page Imprimée",
  //       value:
  //         "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
  //     },
  //     {
  //       label: "Alimentation-courant",
  //       value:
  //         "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
  //     },
  //     {
  //       label: "Type de Papier pris en charge",
  //       value:
  //         "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
  //     },
  //     {
  //       label: "Consommation électrique",
  //       value:
  //         "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
  //     },
  //     {
  //       label: "Cycle d utilisation Mensuel",
  //       value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
  //     },
  //     {
  //       label: "Alimentation papier standard",
  //       value:
  //         "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
  //     },
  //     { label: "Ecran Tactile", value: "Non" },
  //     { label: "Type ecran", value: "7 segments et icône LCD" },
  //     {
  //       label: "Volume de Pages Mensuel Recommandé",
  //       value: "400 à 800 (Jusqu'à 1000 pages)",
  //     },
  //     { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
  //     { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
  //     { label: "Grammage", value: "75 g/m²" },
  //     {
  //       label: "Contenu de L'emballage",
  //       value:
  //         "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
  //     },
  //     { label: "Poids", value: "4,67 kg" },
  //     { label: "Couleur", value: "Noir" },
  //     { label: "Dimensions", value: "525 x 310 x 158 mm" },
  //     { label: "Garantie", value: "1 an" },
  //   ],
  // },
  // {
  //   _id: "ricoh4",
  //   img: ricoh4,
  //   productName: "IMPRIMANTE RICOH COULEUR LASER SPC840",
  //   price: "450",
  //   color: "Blanc",
  //   badge: true,
  //   brand: "Ricoh",
  //   des: "Imprimante à Réservoir intégré HP Ink Tank 315 - Fonctions: Impression, copier, Numérisation - Format Papier: A4 - Technologie d'impression: jet d'encre thermique HP - Vitesse d'impression: Jusqu'à 19 ppm (Noir), Jusqu'à 15 ppm (couleur) - Résolution d'impression: 1200 x 1200 dpi(couleur), 4800 x 1200 dpi(noir) - Vitesse de copie(A4, ISO): 6,5 cpm Noir; 2 cpm Couleur - Vitesse de numérisation A4: Jusqu'à 21 secondes - Impression recto verso Manuelle - Formats de fichiers pour la numérisation: JPEG, TIFF, PDF, BMP, PNG - Vitesse du processeur: 360 MHz - Connectivité: USB  - Dimensions: 525 x 310 x 158 mm - Poids: 4,67 kg - Garantie: 1 an",
  //   cat: "Imprimante",
  //   pdf: pdf1,
  //   ficheTech: [
  //     { label: "DISPONIBILITÉ", value: "En stock" },
  //     { label: "gtin", value: "Z4B04A" },
  //     { label: "Marque", value: "HP" },
  //     { label: "Destockage", value: "Non" },
  //     { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
  //     { label: "fonctions", value: "Multifonction" },
  //     { label: "Impression", value: "Couleur" },
  //     { label: "Mémoire", value: "Non" },
  //     { label: "FAX", value: "Non" },
  //     { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
  //     { label: "Chargement de Documents", value: "Oui" },
  //     { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
  //     { label: "Vitesse du Processeur", value: "360 MHz" },
  //     {
  //       label: "Impression sans bordure",
  //       value: "Oui, jusqu’à 210 x 297 mm (A4)",
  //     },
  //     { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
  //     { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
  //     {
  //       label: "Résolution d'impression Noir",
  //       value: "Jusqu'à 1 200 x 1 200 DPI",
  //     },
  //     {
  //       label: "Résolution d impression Couleur",
  //       value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
  //     },
  //     {
  //       label: "Résolution d impression",
  //       value:
  //         "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
  //     },
  //     { label: "Type de Scanner", value: "Scanner à Plat" },
  //     { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
  //     { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
  //     {
  //       label: "Résolution de numérisation optimisée",
  //       value: "Jusqu’à 1200 ppp",
  //     },
  //     { label: "Recto/Verso", value: "Manuel" },
  //     { label: "Connectivite", value: "USB" },
  //     { label: "formats", value: "A4" },
  //     {
  //       label: "Premiére Page Imprimée",
  //       value:
  //         "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
  //     },
  //     {
  //       label: "Alimentation-courant",
  //       value:
  //         "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
  //     },
  //     {
  //       label: "Type de Papier pris en charge",
  //       value:
  //         "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
  //     },
  //     {
  //       label: "Consommation électrique",
  //       value:
  //         "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
  //     },
  //     {
  //       label: "Cycle d utilisation Mensuel",
  //       value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
  //     },
  //     {
  //       label: "Alimentation papier standard",
  //       value:
  //         "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
  //     },
  //     { label: "Ecran Tactile", value: "Non" },
  //     { label: "Type ecran", value: "7 segments et icône LCD" },
  //     {
  //       label: "Volume de Pages Mensuel Recommandé",
  //       value: "400 à 800 (Jusqu'à 1000 pages)",
  //     },
  //     { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
  //     { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
  //     { label: "Grammage", value: "75 g/m²" },
  //     {
  //       label: "Contenu de L'emballage",
  //       value:
  //         "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
  //     },
  //     { label: "Poids", value: "4,67 kg" },
  //     { label: "Couleur", value: "Noir" },
  //     { label: "Dimensions", value: "525 x 310 x 158 mm" },
  //     { label: "Garantie", value: "1 an" },
  //   ],
  // },
  // {
  //   _id: "ricoh5",
  //   img: ricoh5,
  //   productName: "IMPRIMANTE RICOH SP4510DN (407313)",
  //   price: "450",
  //   color: "Blanc",
  //   badge: true,
  //   brand: "Ricoh",
  //   des: "Imprimante à Réservoir intégré HP Ink Tank 315 - Fonctions: Impression, copier, Numérisation - Format Papier: A4 - Technologie d'impression: jet d'encre thermique HP - Vitesse d'impression: Jusqu'à 19 ppm (Noir), Jusqu'à 15 ppm (couleur) - Résolution d'impression: 1200 x 1200 dpi(couleur), 4800 x 1200 dpi(noir) - Vitesse de copie(A4, ISO): 6,5 cpm Noir; 2 cpm Couleur - Vitesse de numérisation A4: Jusqu'à 21 secondes - Impression recto verso Manuelle - Formats de fichiers pour la numérisation: JPEG, TIFF, PDF, BMP, PNG - Vitesse du processeur: 360 MHz - Connectivité: USB  - Dimensions: 525 x 310 x 158 mm - Poids: 4,67 kg - Garantie: 1 an",
  //   cat: "Imprimante",
  //   pdf: pdf1,
  //   ficheTech: [
  //     { label: "DISPONIBILITÉ", value: "En stock" },
  //     { label: "gtin", value: "Z4B04A" },
  //     { label: "Marque", value: "HP" },
  //     { label: "Destockage", value: "Non" },
  //     { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
  //     { label: "fonctions", value: "Multifonction" },
  //     { label: "Impression", value: "Couleur" },
  //     { label: "Mémoire", value: "Non" },
  //     { label: "FAX", value: "Non" },
  //     { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
  //     { label: "Chargement de Documents", value: "Oui" },
  //     { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
  //     { label: "Vitesse du Processeur", value: "360 MHz" },
  //     {
  //       label: "Impression sans bordure",
  //       value: "Oui, jusqu’à 210 x 297 mm (A4)",
  //     },
  //     { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
  //     { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
  //     {
  //       label: "Résolution d'impression Noir",
  //       value: "Jusqu'à 1 200 x 1 200 DPI",
  //     },
  //     {
  //       label: "Résolution d impression Couleur",
  //       value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
  //     },
  //     {
  //       label: "Résolution d impression",
  //       value:
  //         "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
  //     },
  //     { label: "Type de Scanner", value: "Scanner à Plat" },
  //     { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
  //     { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
  //     {
  //       label: "Résolution de numérisation optimisée",
  //       value: "Jusqu’à 1200 ppp",
  //     },
  //     { label: "Recto/Verso", value: "Manuel" },
  //     { label: "Connectivite", value: "USB" },
  //     { label: "formats", value: "A4" },
  //     {
  //       label: "Premiére Page Imprimée",
  //       value:
  //         "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
  //     },
  //     {
  //       label: "Alimentation-courant",
  //       value:
  //         "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
  //     },
  //     {
  //       label: "Type de Papier pris en charge",
  //       value:
  //         "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
  //     },
  //     {
  //       label: "Consommation électrique",
  //       value:
  //         "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
  //     },
  //     {
  //       label: "Cycle d utilisation Mensuel",
  //       value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
  //     },
  //     {
  //       label: "Alimentation papier standard",
  //       value:
  //         "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
  //     },
  //     { label: "Ecran Tactile", value: "Non" },
  //     { label: "Type ecran", value: "7 segments et icône LCD" },
  //     {
  //       label: "Volume de Pages Mensuel Recommandé",
  //       value: "400 à 800 (Jusqu'à 1000 pages)",
  //     },
  //     { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
  //     { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
  //     { label: "Grammage", value: "75 g/m²" },
  //     {
  //       label: "Contenu de L'emballage",
  //       value:
  //         "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
  //     },
  //     { label: "Poids", value: "4,67 kg" },
  //     { label: "Couleur", value: "Noir" },
  //     { label: "Dimensions", value: "525 x 310 x 158 mm" },
  //     { label: "Garantie", value: "1 an" },
  //   ],
  // },

  // =================== imprimante ricoh =================

  // {
  //   _id: "espson1",
  //   img: espson1,
  //   productName: "IMPRIMANTE EPSON L3251 3EN1 A4 WIFI",
  //   price: "450",
  //   color: "Blanc",
  //   badge: true,
  //   brand: "Epson",
  //   des: "Imprimante à Réservoir intégré HP Ink Tank 315 - Fonctions: Impression, copier, Numérisation - Format Papier: A4 - Technologie d'impression: jet d'encre thermique HP - Vitesse d'impression: Jusqu'à 19 ppm (Noir), Jusqu'à 15 ppm (couleur) - Résolution d'impression: 1200 x 1200 dpi(couleur), 4800 x 1200 dpi(noir) - Vitesse de copie(A4, ISO): 6,5 cpm Noir; 2 cpm Couleur - Vitesse de numérisation A4: Jusqu'à 21 secondes - Impression recto verso Manuelle - Formats de fichiers pour la numérisation: JPEG, TIFF, PDF, BMP, PNG - Vitesse du processeur: 360 MHz - Connectivité: USB  - Dimensions: 525 x 310 x 158 mm - Poids: 4,67 kg - Garantie: 1 an",
  //   cat: "Imprimante",
  //   pdf: pdf1,
  //   ficheTech: [
  //     { label: "DISPONIBILITÉ", value: "En stock" },
  //     { label: "gtin", value: "Z4B04A" },
  //     { label: "Marque", value: "HP" },
  //     { label: "Destockage", value: "Non" },
  //     { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
  //     { label: "fonctions", value: "Multifonction" },
  //     { label: "Impression", value: "Couleur" },
  //     { label: "Mémoire", value: "Non" },
  //     { label: "FAX", value: "Non" },
  //     { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
  //     { label: "Chargement de Documents", value: "Oui" },
  //     { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
  //     { label: "Vitesse du Processeur", value: "360 MHz" },
  //     {
  //       label: "Impression sans bordure",
  //       value: "Oui, jusqu’à 210 x 297 mm (A4)",
  //     },
  //     { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
  //     { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
  //     {
  //       label: "Résolution d'impression Noir",
  //       value: "Jusqu'à 1 200 x 1 200 DPI",
  //     },
  //     {
  //       label: "Résolution d impression Couleur",
  //       value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
  //     },
  //     {
  //       label: "Résolution d impression",
  //       value:
  //         "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
  //     },
  //     { label: "Type de Scanner", value: "Scanner à Plat" },
  //     { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
  //     { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
  //     {
  //       label: "Résolution de numérisation optimisée",
  //       value: "Jusqu’à 1200 ppp",
  //     },
  //     { label: "Recto/Verso", value: "Manuel" },
  //     { label: "Connectivite", value: "USB" },
  //     { label: "formats", value: "A4" },
  //     {
  //       label: "Premiére Page Imprimée",
  //       value:
  //         "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
  //     },
  //     {
  //       label: "Alimentation-courant",
  //       value:
  //         "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
  //     },
  //     {
  //       label: "Type de Papier pris en charge",
  //       value:
  //         "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
  //     },
  //     {
  //       label: "Consommation électrique",
  //       value:
  //         "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
  //     },
  //     {
  //       label: "Cycle d utilisation Mensuel",
  //       value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
  //     },
  //     {
  //       label: "Alimentation papier standard",
  //       value:
  //         "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
  //     },
  //     { label: "Ecran Tactile", value: "Non" },
  //     { label: "Type ecran", value: "7 segments et icône LCD" },
  //     {
  //       label: "Volume de Pages Mensuel Recommandé",
  //       value: "400 à 800 (Jusqu'à 1000 pages)",
  //     },
  //     { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
  //     { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
  //     { label: "Grammage", value: "75 g/m²" },
  //     {
  //       label: "Contenu de L'emballage",
  //       value:
  //         "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
  //     },
  //     { label: "Poids", value: "4,67 kg" },
  //     { label: "Couleur", value: "Noir" },
  //     { label: "Dimensions", value: "525 x 310 x 158 mm" },
  //     { label: "Garantie", value: "1 an" },
  //   ],
  // },

  // {
  //   _id: "espson2",
  //   img: espson2,
  //   productName: "IMPRIMANTE EPSON JET D'ENCRE L3156 COULEUR A4  WIFI",
  //   price: "450",
  //   color: "Blanc",
  //   badge: true,
  //   brand: "Epson",
  //   des: "Imprimante à Réservoir intégré HP Ink Tank 315 - Fonctions: Impression, copier, Numérisation - Format Papier: A4 - Technologie d'impression: jet d'encre thermique HP - Vitesse d'impression: Jusqu'à 19 ppm (Noir), Jusqu'à 15 ppm (couleur) - Résolution d'impression: 1200 x 1200 dpi(couleur), 4800 x 1200 dpi(noir) - Vitesse de copie(A4, ISO): 6,5 cpm Noir; 2 cpm Couleur - Vitesse de numérisation A4: Jusqu'à 21 secondes - Impression recto verso Manuelle - Formats de fichiers pour la numérisation: JPEG, TIFF, PDF, BMP, PNG - Vitesse du processeur: 360 MHz - Connectivité: USB  - Dimensions: 525 x 310 x 158 mm - Poids: 4,67 kg - Garantie: 1 an",
  //   cat: "Imprimante",
  //   pdf: pdf1,
  //   ficheTech: [
  //     { label: "DISPONIBILITÉ", value: "En stock" },
  //     { label: "gtin", value: "Z4B04A" },
  //     { label: "Marque", value: "HP" },
  //     { label: "Destockage", value: "Non" },
  //     { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
  //     { label: "fonctions", value: "Multifonction" },
  //     { label: "Impression", value: "Couleur" },
  //     { label: "Mémoire", value: "Non" },
  //     { label: "FAX", value: "Non" },
  //     { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
  //     { label: "Chargement de Documents", value: "Oui" },
  //     { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
  //     { label: "Vitesse du Processeur", value: "360 MHz" },
  //     {
  //       label: "Impression sans bordure",
  //       value: "Oui, jusqu’à 210 x 297 mm (A4)",
  //     },
  //     { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
  //     { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
  //     {
  //       label: "Résolution d'impression Noir",
  //       value: "Jusqu'à 1 200 x 1 200 DPI",
  //     },
  //     {
  //       label: "Résolution d impression Couleur",
  //       value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
  //     },
  //     {
  //       label: "Résolution d impression",
  //       value:
  //         "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
  //     },
  //     { label: "Type de Scanner", value: "Scanner à Plat" },
  //     { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
  //     { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
  //     {
  //       label: "Résolution de numérisation optimisée",
  //       value: "Jusqu’à 1200 ppp",
  //     },
  //     { label: "Recto/Verso", value: "Manuel" },
  //     { label: "Connectivite", value: "USB" },
  //     { label: "formats", value: "A4" },
  //     {
  //       label: "Premiére Page Imprimée",
  //       value:
  //         "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
  //     },
  //     {
  //       label: "Alimentation-courant",
  //       value:
  //         "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
  //     },
  //     {
  //       label: "Type de Papier pris en charge",
  //       value:
  //         "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
  //     },
  //     {
  //       label: "Consommation électrique",
  //       value:
  //         "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
  //     },
  //     {
  //       label: "Cycle d utilisation Mensuel",
  //       value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
  //     },
  //     {
  //       label: "Alimentation papier standard",
  //       value:
  //         "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
  //     },
  //     { label: "Ecran Tactile", value: "Non" },
  //     { label: "Type ecran", value: "7 segments et icône LCD" },
  //     {
  //       label: "Volume de Pages Mensuel Recommandé",
  //       value: "400 à 800 (Jusqu'à 1000 pages)",
  //     },
  //     { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
  //     { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
  //     { label: "Grammage", value: "75 g/m²" },
  //     {
  //       label: "Contenu de L'emballage",
  //       value:
  //         "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
  //     },
  //     { label: "Poids", value: "4,67 kg" },
  //     { label: "Couleur", value: "Noir" },
  //     { label: "Dimensions", value: "525 x 310 x 158 mm" },
  //     { label: "Garantie", value: "1 an" },
  //   ],
  // },
];